### ISSUE TITLE
75 Jahre Seite

### ISSUE THREAD

**Issue by slazar1992** [mseele/sve-website#283]
@mseele kannst Du die Fitnessschupperkurse bitte bei der Übersicht am Samstag mit einfügen?

13 Uhr: Schnupperkurs Fitmix und Pilates (kostenlos, 1 Stunde)
15:30 Uhr: Schnupperkurs Rückenfit und Zumba (kostenlos, 1 Stunde)

**Comment by mseele** [comment]
Ich hab den Text verbessert
