### ISSUE TITLE
Trainer-Kontakte überarbeiten

### ISSUE THREAD

**Issue by slazar1992** [mseele/sve-website#285]
Hi Waldi,

hier erste Trainer-Kontakte, die wir aktualisieren müssen. Weitere folgen Ende August...

Liebe Grüße
Smillo

Herren

1. Mannschaft

Trainer: Alexander Esslinger

Sonst alles gleich

2. Mannschaft

Trainer: Yannik Janzen

3. Mannschaft

Spielklasse: B2 Reserve

Trainer: Yannik Janzen 

Frauen

1. Mannschaft

Spielklasse: Landesliga

2. Mannschaft

Spielklasse: Regionenliga

**Comment by mseele** [comment]
Danke. Ich benötige hier noch die Kontaktmöglichkeiten:
- Mobilfunk
- Email

**Comment by slazar1992** [comment]
bei Mail bitte jeweils dneuss87@gmail.com  nehmen

und bei Mobil:
Alex: +49 163 8184870
Yannik: +49 163 7296476
